### ISSUE TITLE
Increase font size of FAB button

### ISSUE THREAD

**Issue by danieldanielecki** [tamotam-com/tamotam-app#2]
Icons are fixed at size 24 in FAB. It would be good to have the size bigger

Follow-up PR [#921](https://github.com/callstack/react-native-paper/pull/921) to track once the issue.

**Comment by jahau** [comment]
Needed.

**Comment by danieldanielecki** [comment]
It looks good on real, `Android, and `iOS` devices.
Not a big need, but could've been improved when the PR https://github.com/callstack/react-native-paper/pull/921 will be fixed.

**Comment by danieldanielecki** [comment]
Done in https://github.com/tamotam-com/tamotam-app/commit/e49da2001194e98dc4b71cfbc85d17da8670f7ab
