### ISSUE TITLE
Error Failed to Install

### ISSUE THREAD

**Issue by putuoka** [tamotam-com/tamotam-app#56]
1. git clone https://github.com/tamotam-com/tamotam-app.git
2. yarn install
3. yarn android

<img width="438" alt="image" src="https://github.com/tamotam-com/tamotam-app/assets/20880839/8084d754-c655-4cdd-9b03-1ef037a4587d">

Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.

**Comment by danieldanielecki** [comment]
`google-services.json` is a personal file, you can get it generated from `Firebase` while creating a project there; I won't add it to the public repo!
